/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import jdbc.AccountConnection;

/**
 * ユーザ名をデータベースに連結する
 *
 * @author linjie 作成日2020/12/07 バージョン　1.0
 */
public class AccountMenu extends javax.swing.JFrame {

    /**
     * Creates new form account
     */
    public AccountMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dcnetLogo = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        tel = new javax.swing.JLabel();
        adress = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        inputUser = new javax.swing.JTextField();
        inputPassword = new javax.swing.JPasswordField();
        inputName = new javax.swing.JTextField();
        inputTel = new javax.swing.JTextField();
        inputMail = new javax.swing.JTextField();
        inputAdress = new javax.swing.JTextField();
        ｒegister = new javax.swing.JButton();
        returnMane = new javax.swing.JButton();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        secret = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dcnetLogo.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        dcnetLogo.setForeground(new java.awt.Color(0, 204, 0));
        dcnetLogo.setText("DCNET　図書管理システム");

        user.setText("ユーザ名");

        password.setText("パスワード");

        mail.setText("メールアドレス");

        tel.setText("電話番号");

        adress.setText("住所");

        name.setText("名前");

        sex.setText("性別");

        inputUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUserActionPerformed(evt);
            }
        });

        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });

        inputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameActionPerformed(evt);
            }
        });

        inputTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTelActionPerformed(evt);
            }
        });

        inputMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMailActionPerformed(evt);
            }
        });

        inputAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAdressActionPerformed(evt);
            }
        });

        ｒegister.setText("登録");
        ｒegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ｒegisterActionPerformed(evt);
            }
        });

        returnMane.setText("戻る");
        returnMane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnManeActionPerformed(evt);
            }
        });

        female.setText("男");

        male.setText("女");

        secret.setText("秘密");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(dcnetLogo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adress, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(inputUser)
                                .addComponent(inputPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addComponent(inputName)
                                .addComponent(inputTel)
                                .addComponent(inputMail)
                                .addComponent(inputAdress))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(female)
                                .addGap(18, 18, 18)
                                .addComponent(male)
                                .addGap(18, 18, 18)
                                .addComponent(secret))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(ｒegister, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(returnMane, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dcnetLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputUser, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputPassword)
                    .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(female)
                    .addComponent(male)
                    .addComponent(secret))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adress, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputMail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnMane, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(ｒegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUserActionPerformed

    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    private void inputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameActionPerformed

    private void inputTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTelActionPerformed

    private void inputMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMailActionPerformed

    private void inputAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAdressActionPerformed

    private void returnManeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnManeActionPerformed

        BookMane bm = new BookMane();
        // BookManeを開いてこの画面を閉じる
        bm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnManeActionPerformed

    private void ｒegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ｒegisterActionPerformed

        // 性別のところひとつしか選択できない
        ButtonGroup group = new ButtonGroup();
        group.add(female);
        group.add(male);
        group.add(secret);
        String userSex;
        if (female.isSelected()) {
            userSex = "男";
        } else if (male.isSelected()) {
            userSex = "女";
        } else if (secret.isSelected()) {
            userSex = "秘密";
        } else {
            // 性別が選択してないときに
            userSex = "";
        }
        // すべての項目の入力が必要
        if (!userSex.isEmpty() && !inputUser.getText().equals("") && !inputPassword.getText().equals("") && !inputName.getText().equals("") && !inputTel.getText().equals("") && !inputAdress.getText().equals("") && !inputMail.getText().equals("")) {

            String sql = "insert into userInfo (users,password,name,sex,tel,adress,mail) values" + "('" + inputUser.getText() + "','" + inputPassword.getText() + "','" + inputName.getText() + "','" + userSex + "','" + inputTel.getText() + "','" + inputAdress.getText() + "','" + inputMail.getText() + "');";
            // 同じユーザがあるかどうかの確認
            String search = "select users from userInfo where users='" + inputUser.getText() + "';";
            AccountConnection ac = new AccountConnection();
            int res = ac.getSameData(search);
            // 同じユーザがなければ登録する
            if (res == 0) {
                // ユーザをデータベースに入れる
                ac.excuteSQLQuery(sql);
                int result = JOptionPane.showConfirmDialog(this, inputUser.getText() + "　が登録しました,ログイン画面に戻りますか", "確認", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (result == JOptionPane.YES_OPTION) {
                    this.dispose();
                    BookMane bm = new BookMane();
                    bm.setVisible(true);
                } else {
                }
            } else {
                // 同じユーザの場合
                JOptionPane.showMessageDialog(this, "ユーザ名が重複です,他のユーザ名を入力してください");
            }

        } else {
            // それぞれ未入力の項目の提示
            if (inputUser.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "ユーザ名を入力してください");
            } else if (inputPassword.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "パスワードを入力してください");
            } else if (inputName.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "名前を入力してください");
            } else if (userSex.equals("")) {
                JOptionPane.showMessageDialog(this, "性別を選んでください");
            } else if (inputTel.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "電話番号を入力してください");
            } else if (inputAdress.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "住所を入力してください");
            } else {
                JOptionPane.showMessageDialog(this, "メールアドレスを入力してください");
            }
        }
    }//GEN-LAST:event_ｒegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adress;
    private javax.swing.JLabel dcnetLogo;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField inputAdress;
    private javax.swing.JTextField inputMail;
    private javax.swing.JTextField inputName;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputTel;
    private javax.swing.JTextField inputUser;
    private javax.swing.JLabel mail;
    private javax.swing.JRadioButton male;
    private javax.swing.JLabel name;
    private javax.swing.JLabel password;
    private javax.swing.JButton returnMane;
    private javax.swing.JRadioButton secret;
    private javax.swing.JLabel sex;
    private javax.swing.JLabel tel;
    private javax.swing.JLabel user;
    private javax.swing.JButton ｒegister;
    // End of variables declaration//GEN-END:variables
}
